### PR TITLE
Change Heading text

### LINKED ISSUE #1: Changed Heading Color
I think green heading color might look more beautiful.

```css

h1 {
color: #44789
}
```

### PR DESCRIPTION
**Pull request by ShaheryarRafique**
As per i create #1 i have changed the color of text and heading too and now it looks beautiful too me.
You can now review @shaheryar478  and merge into the master branch.

### CODE REVIEW

**Review by shaheryar478 — COMMENTED** [review]
- I Heading Text need to be more specific.

**Comment by ShaheryarRafique** [comment]
> * I Heading Text need to be more specific.

Oky Let me do this

**Review by shaheryar478 — APPROVED** [review]
Yeah that's good.

**Comment by ShaheryarRafique** [comment]
Great!

**Pull request merged**
